name: segway
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3
  - segway
  - six
  - genomedata
  - gmtk
  - autolog
  - textinput
  - optbuild
  - optplus
  - path.py
  - colorbrewer
  - drmaa>=0.4a3
  - ucsc-bedtobigbed

