gmtkEMtrain \
    -cppCommandOptions "-DCARD_SEG=4 -DCARD_FRAMEINDEX=2000000 -DSEGTRANSITION_WEIGHT_SCALE=1.0 -DCARD_SUBSEG=1" \
    -dirichletPriors T \
    -fmt1 binary \
    -inputMasterFile input.master \
    -iswp1 F \
    -island T \
    -lst 100000 \
    -maxEmIters 1 \
    -nf1 2 \
    -ni1 0 \
    -objsNotToTrain dont_train.list \
    -obsNAN T \
    -of1 float32.list \
    -storeAccFile acc.0.0.bin \
    -strFile segway.str \
    -triFile segway.str.4.1.trifile \
    -trrng 0 \
    -verbosity 30
