name: Build and Test

# Workflow is triggered only on push to the master branch or a pull request to
# the master branch

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Run job for both python versions in the docker image
    container:
      image: hoffmanlab/segway-test:latest
      env:
        SEGWAY_TEST_PYTHON_VERSION: 3

    steps:
      - uses: actions/checkout@v2
      - name: Build repository
        run: |
          python${SEGWAY_TEST_PYTHON_VERSION} -m pip install --verbose .
          pip list
      - name: Run tests
        run: |
          gmtkPrint -version
          cd test && ./test_all.sh
      - name: Capture test results on failure
        if: ${{ failure () }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test/**/*-changes.tar.gz