name: Build and Test

# Workflow is triggered only on push to the master branch or a pull request to
# the master branch

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Run job for both python versions in the docker image
    container:
      image: hoffmanlab/segway-test:latest
      env:
        SEGWAY_TEST_PYTHON_VERSION: 3

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install test dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools build pyflakes
      - name: Build repository
        run: |
          python3 -m build
      - name: Install
        run: |
          python3 -m pip install -v .
          pip list
      - name: Run tests
        run: |
          gmtkPrint -version
          cd test && ./test_all.sh
      - name: Capture test results on failure
        if: ${{ failure () }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test/**/*-changes.tar.gz
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: segway-build
          path: dist/*